### ISSUE TITLE
Game Crashes and Cannot Load After Trying To Adjust Car Noise in Sounds

### ISSUE THREAD

**Issue by DrEpicSquidness** [henkelmax/ultimate-car-mod#111]
**Bug description**

**Steps to reproduce the issue**
1. Go to the Minecraft Sounds Tab
2. Click on Car Noise
3. Scroll down to Raise it up from its apparent default 23
4. Watch one's game explode.

**Expected behavior**
I expected to be able to freely adjust the slider. 

**Log files**
https://mclo.gs/SMYxyA6 -Crash Report
https://mclo.gs/zKTceDv -latest.log

**Versions**
- MC 1.19.2
- 43.1.3
- 1.19.2-1.0.0

**Other mods**
(https://docs.google.com/document/d/1uKc63U3ILqtxfi6nAxfYYcGIaauXV7TP366-rcD-cbY/edit?usp=sharing)

**Comment by henkelmax** [comment]
The crash is caused by Forges config system:

`The process cannot access the file because it is being used by another process`

The car mod tries to save the new volume to the config, but Forges config system fails saving the file. This could be caused by having the file open in an editor or having the game open multiple times.
