### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by momo-i2** [henkelmax/ultimate-car-mod#181]
### Bug description

**"Back"** in "Car Workshop" (return to previous screen **"action"**) and **"Back"** in "Sign"(**"direction"** of the sign) are different meaning in Japanese. So, I'm unable to translate this key exactly.

### Minecraft version

1.21.1

### Mod version

1.21.1-1.0.32

### Mod loader and version

neoforge 21.1.80

### Steps to reproduce

1. translate "gui.sign.back" and "button.car.back"
2. open Repair Car in Car Workshop and check translated key (this must be translating "戻る")
3. open Sign and check translated key (this must be translating "後ろ)

### Log files

N/A

### Screenshots

The red underline in the first image is the faulty part, and it should be translated as shown in the red underline in the second image.
![image](https://github.com/user-attachments/assets/04f65317-1c85-4e22-a6e6-359c6e27d424)
![image](https://github.com/user-attachments/assets/b7f06145-862a-4702-955f-261829aa7afc)

**Comment by rinfromniigata** [comment]
I faced the same problem.
I have dealt with it by writing `バック` in my fork, but I would like to use a different way of saying it if possible.
I would like to see a response.

**Comment by rinfromniigata** [comment]
I looked at the commit of `guisign.java`, and I don't think just changing the reference to the button on line 69 is sufficient. The part after that, where the `front` bool switches the display, also needs to be rewritten.
I hope you also change `button.car.back` in line 78 to `gui.sign.back`, and change `button.car.front` in line 84 to `gui.sign.front`.
In the current version `1-0-33`, only the first `guisign` displayed is correct, and after that, if you switch even once, both will revert back to their original wrong display.
It's no wonder it's hard to understand because in English both of them are written the same, for which I apologize as a Japanese speaker. Anyway, that's why I hope for an additional correction.
Thanks again.

Translated with DeepL.com (free version)

**Comment by henkelmax** [comment]
Sorry for the oversight, thanks for pointing that out!

**Comment by momo-i2** [comment]
Thank you very much for your prompt improvement. I have also been working on a Japanese translation, and I see that a different PR has already been submitted, so I appreciate that as well.
However, I may make some comments in the PR if I find something I like.
