### ISSUE TITLE
models and textures

### ISSUE THREAD

**Issue by KraftLarence** [henkelmax/ultimate-car-mod#91]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/car/faq)!**
How do you change models? I am using blender and mesh lab, but my new textures are poor wraps and even though I add different 3d object models its still shows the same ones? Thank you for all your time and consideration. It is a wonderful mod!

**Comment by henkelmax** [comment]
You would need to switch out the `.obj` files. I'm not sure if this is possible with a resource pack. You would need to replace the files in the mod .jar

**Comment by KraftLarence** [comment]
Well that is very interesting. In mine they are .MTL files, is it bad they aren't .obj? I have switched them though. Sorry if I worded it poorly, but that's what got me stumped.

**Comment by henkelmax** [comment]
It has to be `.obj` The parsing of these files is also very restricted, so you might need to tweak some export parameters in blender.
I won't explain the limitations and stuff here, since switching models is not officially supported. If you want to see how it works, you can always read the source code.

**Comment by KraftLarence** [comment]
I understand your reasoning completely, and that reply has been such a huge help. I knew something was just off when it kept popping the same model and that explains it. I will try to understand the source code. Thank you so much!
